version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
        fingerprints:
          - "73:88:17:45:5c:88:82:a9:d0:63:92:4f:e6:22:75:4c"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build
